Git:
  FilePath: /usr/local/bin/git
  Website: https://github.com/
  UrlSuffix: .git
MirrorUrl:
  - https://hub.fastgit.org/
  - https://gitclone.com/
  - https://github.wuyanzheshui.workers.dev/
  - https://github.com.cnpmjs.org/