Git:
  FilePath: /usr/local/bin/git
  Website: https://github.com/
  UrlSuffix: .git
MirrorUrl:
  - https://hub.fastgit.xyz/
  - https://hub.fastgit.org/
  - https://gitclone.com/
  - https://github.wuyanzheshui.workers.dev/
  - https://github.com.cnpmjs.org/
  - https://ghproxy.com/
  - https://hub.おうか.tw/
  - https://hub.連接.台灣/
  - https://www.github.do/